python3 experiment.py cnf/sudoku/top870.sdk.txt &
python3 experiment.py cnf/sudoku/top870.sdk.txt &
python3 experiment.py cnf/sudoku/top870.sdk.txt &
python3 experiment.py cnf/sudoku/top870.sdk.txt &
python3 experiment.py cnf/sudoku/top870.sdk.txt &
python3 experiment.py cnf/sudoku/top870.sdk.txt &
python3 experiment.py cnf/sudoku/top870.sdk.txt &
python3 experiment.py cnf/sudoku/top870.sdk.txt &
python3 experiment.py cnf/sudoku/top870.sdk.txt &
python3 experiment.py cnf/sudoku/top870.sdk.txt &
